### PR TITLE
Issue #48 - Tagwise runners

### PR DESCRIPTION
**Pull request by temyers**

### CODE REVIEW

**Comment by sugatmankar** [comment]
@temyers  this branch has complete different implementation in CucumberItGenerator.java.

please run it separately from master branch. 

I also tried to resolved conflicts with master branch but there are too many changes.

**Comment by temyers** [comment]
@sugatmankar Cheers for the contribution.

There are a bunch of changes here:
Can you point me at the appropriate files to review?
Have the code bases diverged too far?  Should I consider a re-implement?

**Comment by sugatmankar** [comment]
@temyers  CucumberItGenerator.java is most changes done and i used Gherkin to parse feature file instead of just searching tag by converting file to string, because of this we will able to do anything any changes we want as per Gherkin, even in feature anything come new in Gherkin it will be easy to add/modify. 

Yes i recommend you to first verify changes and consider re-implementation.

**Comment by temyers** [comment]
Ok great, cheers

**Comment by sugatmankar** [comment]
Hey @temyers i have created another branch tagwiseOutlinewise 
 https://github.com/sugatmankar/cucumber-jvm-parallel-plugin/tree/tagwiseOutlinewise 

Now there are some changes in velocity templates as well as in IT files also.
We can generate Scenario Outline wise runners.

@examples
Scenario Outline: four outline runner should be generated
 Given I have <Header>
     Examples:
        |   Header  |
22    | example1 |
23    | example2 |
24    | example3 |
25    | example4 |


Configurations in pom file : 
<tags>"@examples"</tags>							<filterScenarioOutlineByLines>true</filterScenarioOutlineByLines>

Output : 

@CucumberOptions(strict = true,
    features = {" ABSOLUTE PATH OF FILE /feature1.feature:22"},
    plugin = {"json:target/cucumber-parallel/1.json", "pretty"},
    monochrome = false,
    glue = { "foo", "bar" })
public class Parallel01IT {
}

@CucumberOptions(strict = true,
    features = {" ABSOLUTE PATH OF FILE /feature1.feature:23"},
    plugin = {"json:target/cucumber-parallel/2.json", "pretty"},
    monochrome = false,
    glue = { "foo", "bar" })
public class Parallel02IT {
}

@CucumberOptions(strict = true,
    features = {" ABSOLUTE PATH OF FILE /feature1.feature:24"},
    plugin = {"json:target/cucumber-parallel/3.json", "pretty"},
    monochrome = false,
    glue = { "foo", "bar" })
public class Parallel03IT {
}

@CucumberOptions(strict = true,
    features = {" ABSOLUTE PATH OF FILE /feature1.feature:24"},
    plugin = {"json:target/cucumber-parallel/4.json", "pretty"},
    monochrome = false,
    glue = { "foo", "bar" })
public class Parallel04IT {
}

**Comment by stevejensen22** [comment]
I would like add this to my project. Is there any way we can get a beta build of it? Per-scenario granularity for parallel test execution would be awesome! If not, if you could point me in the right direction to build it and add it to my project I would appreciate it!

**Comment by temyers** [comment]
This is still very much a work in progress and needs reviewing and re-implementing before it would be ready to merge.

I'd recommend forking @sugatmankar https://github.com/sugatmankar/cucumber-jvm-parallel-plugin/tree/tagwiseOutlinewise repository to build and test.

**Comment by sugatmankar** [comment]
@stevejensen22 untill final merge follow below steps:-
1. git clone -b tagwiseOutlinewiseIssueRerun https://github.com/sugatmankar/cucumber-jvm-parallel-plugin.git
2. cd to cloned directory and hit command "mvn clean install "
3. update your pom file with 
`<dependencies>
    <dependency>
        <groupId>com.github.temyers</groupId>
          <artifactId>cucumber-jvm-parallel-plugin</artifactId>
          <version>1.3.0-SNAPSHOT</version>
    </dependency>
</dependencies>

<plugin>
  <groupId>com.github.temyers</groupId>
  <artifactId>cucumber-jvm-parallel-plugin</artifactId>
  <version>1.2.1</version>
  <executions>
    <execution>
      <id>generateRunners</id>
      <phase>validate</phase>
      <goals>
        <goal>generateRunners</goal>
      </goals>
      <configuration>
          
          
         <glue>foo, bar</glue>
         
          
           <outputDirectory>${project.build.directory}/generated-test-sources/cucumber</outputDirectory>
           
          <featuresDirectory>src/test/resources/features/</featuresDirectory>
           
          <cucumberOutputDir>target/cucumber-parallel</cucumberOutputDir>
          
         <format>json,html,rerun</format>
         
         <strict>true</strict>
         
         <monochrome>true</monochrome>
         
         <tags>"@complete", "@accepted"</tags>
         
         
         <filterFeaturesByTags>false</filterFeaturesByTags>
          
         <useTestNG>false</useTestNG>
          
         <namingScheme>simple</namingScheme>
         
         <namingPattern>Parallel{c}IT</namingPattern>
         
         <retryCount>0</retryCount>
        <filterScenarioOutlineByLines>true</filterScenarioOutlineByLines>
      </configuration>
    </execution>
  </executions>
</plugin>`

**Comment by stevejensen22** [comment]
@sugatmankar: Does your branch work for running `Scenarios` in the same `Feature` in parallel (not in a scenario outline)? If so, how do I configure my pom to make that work? Currently, it appears to be generating a Runner class per scenario, but all the runners generated that reference a single `.feature` file are identical, and therefore, maven is running a bunch of duplicate scenarios.

**Comment by sugatmankar** [comment]
@stevejensen22  Thanks for pointing issue. I was missed this cross check. Today i have fixed it. Please update and use same way that you mentioned. Now it will not generate duplicate runner.

**Comment by sugatmankar** [comment]
@temyers I agree with generic approach of Cucumber, if no tags provide then all tags runner should be generated. I have restricted this approach because of following reason.

 Suppose a Scenario or Scenario Outline is tagged with multiple tags 
image
In this eg 5 runner will get generate if we follow blank tag approach.

If project has bunch of features with bunch of Scenarios and Scenario Outlines and each tagged with multiple tags and if we don't provide tags then duplicate runners will be generated and this is meaning less to keep running as well as re-running also. So i think it will be good if we restrict users from adding blank tags. This branch has _compulsion of tags_, user must pass tags either in pom file or override it while running from command line.

**Comment by sugatmankar** [comment]
@temyers  Bingo ..! while thinking about support for generic approach i got solution, i was very near to skip those duplication, if i use Gherkin to parse all tags and select only one from multiple, i would be able to do what is recommended, Yes i did it, _Thanks Gherkin it is very easy to control any requirement with the help of it._

Now if no tags are specified, this branch will be able to generate all runner per tag present in project.
Only one **_compulsion_** is there **_Scenario or Scenario Outline must be tagged with at least one tag._**

Now this branch has almost everything what we were expecting.

**Comment by sugatmankar** [comment]
@stevejensen22 please try now by getting latest update , let me know if you face any issue.

**Comment by stevejensen22** [comment]
My new runners look like this:

```
@CucumberOptions(strict = true,
          features = {"src/test/resources/skeleton/features/mbo/MBO Place Personal Order.feature"},
       tags = {"@automated"},
       plugin = {"json:target/1.json", "pretty"},
    monochrome = false,
    glue = { "skeleton.stepdefs" })
public class ParallelRunner01 extends AbstractTestNGCucumberTests {
}
```

```
@CucumberOptions(strict = true,
          features = {"src/test/resources/skeleton/features/mbo/MBO Place Personal Order.feature"},
       tags = {"@automated"},
       plugin = {"json:target/2.json", "pretty"},
    monochrome = false,
    glue = { "skeleton.stepdefs" })
public class ParallelRunner02 extends AbstractTestNGCucumberTests {
}
```

**Comment by sugatmankar** [comment]
@stev could you provide feature file. I think you have tagged Scenario with same @automated tag. Tags must be unique.

**Comment by stevejensen22** [comment]
So I need to generate a unique tag for every scenario? All my scenarios share an `@automated` tag and then differ by application or priority. ie: `@checkout` `@high`.

**Comment by sugatmankar** [comment]
Yes put first tag unique like @12345 @automated.

**Comment by stevejensen22** [comment]
Here's a snippet from my feature file:
```
@mbo3 @high
Feature: Place Personal Orders in the Member Back Office
    I will be in My Orders Place Personal Order
    Testing Addresses and Credit Cards

    Background:
        Given I am a valid user
        And I have started a browser
        And I have logged
        And I have navigated to "place a personal order"
        And I select a random product on the page
        And I navigate to my shopping cart
        And I check out from the shopping cart page

    @automated
    Scenario: Place Personal Order, New Address and Existing Credit Card
        Given I have a credit card saved to my account
        And I have added a new shipping address manually
#            | information    |
#            | Full Name      |
#            | Address Line 1 |
#            | Zip Code       |
#            | City           |
#            | State          |
#            | Phone          |
        And I select a credit card and continue
        And I place my order
        Then I am taken to the order summary page

    @automated
    Scenario: Place Personal Order, New Address and New Credit Card
        Given I have added a new shipping address manually
        And I add a credit card manually
#            | information        |
#            | Name on Card       |
#            | Credit Card Number |
#            | Expiration Date    |
#            | Billing Address    |
#            | Billing City       |
#            | Billing State      |
#            | Billing Zip Code   |
#            | Billing Country    |
#            | CVV2 Security Code |
        And I place my order
        Then I am taken to the order summary page
```

**Comment by stevejensen22** [comment]
> Yes put first tag unique like @12345 @automated.

So how do I use the `<tags>` config option if all my tags are unique?

**Comment by sugatmankar** [comment]
I tried hard for single tag on each Scenario but duplication raise . To achieve tag wise tag must unique.  Outline won't allow as u mentioned.
features = {"src/test/resources/skeleton/features/mbo/MBO Place Personal Order.feature:16"},
       tags = {"~@ignore", "@automated", "@high"}

If you provide line no followed by :line no , tags option can't be there.

**Comment by sugatmankar** [comment]
<tags> @tag1, @tag2 , @tag3 ,..... Comma separated tags <tags>

**Comment by stevejensen22** [comment]
So I need to remove the `<tags>` config from my `pom.xml`?

**Comment by sugatmankar** [comment]
@stevejensen22 No you don't need to remove <tag> config. Keep it as 
`<tags>"~@ignore", "${env.tag}"</tags>`
And pass all tags that you want to run in command line.
like `mvn clean verify -Denv.tag="@tag1,@tag2,@tag3,@all tags comma separated that you want to run"`

**Comment by stevejensen22** [comment]
Just tried this today and it is almost PERFECT!!!

The only thing I've seen is that `<tags>"@automated","~@ignore", "${env.tag}"</tags>` appears to be treating those values as `OR`'s instead of `AND`'s.

So that config generates a runner class for any feature that has `@automated` OR `@${env.tag}` thus generating way more classes than is needed

I think that just needs to be tweaked. 
For cucumber: 
`"@automated", "@high"` should be `AND` 
while 
`"@automated, @high"` should be `OR`.

Thank you so much!! This is awesome!

**Comment by stevejensen22** [comment]
Also found that using `Examples` specific tags also is not supported. ie:
```
    Scenario Outline: Do something with <otg nfr>
        Given I do something with <otg nfr>

        @automated
        Examples:
            | otg nfr |
            | otg     |

        @Jira @broken
        Examples:
            | otg nfr |
            | nfr     |
```

**Comment by sugatmankar** [comment]
Welcome @stevejensen22  ... I need to test more about AND OR cases ,  Scenario Outline with multiple examples i didn't added it yet. Wait for that else you are welcome to add those changes to my repository by forking it.
:)

**Comment by SasidharParnandi** [comment]
@sugatmankar : Following your response to my comment at https://github.com/temyers/cucumber-jvm-parallel-plugin/pull/30
I got [tagwiseOutlinewiseIssueRerun ](https://github.com/sugatmankar/cucumber-jvm-parallel-plugin/tree/tagwiseOutlinewise) branch and tried to check re-run functionality. 
**It doesn't work.** 
When I set retryCount in config to any non zero value, I can see errors. The exception is in the runner class. When I looked at the runners, I found that the wrong arguments are passed to ReportBuilder when building the consolidating the report.

I use the same ReportBuilder locally and can confirm the exception is valid. Not sure if this is ReportBuilder version issue. I checked on 2.2(which I use) as well as 2.8 latest.

Exception :

_Parallel01IT.java:[251,43] constructor ReportBuilder in class net.masterthought.cucumber.ReportBuilder cannot be applied to given types;
[ERROR] required: java.util.List<java.lang.String>,net.masterthought.cucumber.Configuration
[ERROR] found: java.util.List<java.lang.String>,java.io.File,java.lang.String,java.lang.String,java.lang.String,boolean,boolean,boolean,boolean,boolean,java.lang.String,boolean
[ERROR] reason: actual and formal argument lists differ in length_

It works if I change retryCount to 0,  but obviously no ReRun functionality.

**Comment by sugatmankar** [comment]
@SasidharParnandi please use java version above 1.7 also check for compiler setting in your IDE. If you are using IntelliJ idea ignore error in pom file. Retry count you can specify only 0 to 5.

**Comment by SasidharParnandi** [comment]
I use Intellij idea and ignored POM errors. I use Java 1.8.
As I said above, I get error when I set retryCount to any non zero i.e. 1 in my case. I can clearly see that the runner class created with rerun functionality has exception in it.

Anyway, for now I have figured out an easy way to handle reruns. In my jenkins job, I have added a post build action to concatenate all the *.rerun files into a single rerun.txt after the maven test. I already have my ReRunFailed runner which I use today for running the failed tests.

**Comment by temyers** [comment]
Re-implemented in #68

**Comment by stevejensen22** [comment]
@temyers: Thank you so much for putting these changes into an official release ([#68](https://github.com/temyers/cucumber-jvm-parallel-plugin/pull/68))! I'm so excited to get your implementation working with my configuration. I had previously used @sugatmankar's [implementation](https://github.com/sugatmankar/cucumber-jvm-parallel-plugin/tree/tagwiseOutlinewise) by compiling the code locally and had everything working except `OR` logic with tags and `SCENARIO` based parallelization.

However, with the latest changes made in 2.0.0...

I can't use `<parallelScheme>SCENARIO</parallelScheme>` with `<tags>"@tag"</tags>` and 
                            `<filterFeaturesByTags>true</filterFeaturesByTags>`.

Here's an example error: 
```
run_cukes(Mboviewmyteamenroll43IT)  Time elapsed: 0.02 sec  <<< FAILURE!
java.lang.IllegalArgumentException: Inconsistent filters: [@staging, 93]. Only one type [line,name,tag] can be used at once.
```

This may be a limitation related to the gherkin parser. Is there any way we can ignore this requirement (`Only one type [line,name,tag] can be used at once.`)? Thanks again! I'll be happy to provide any other information you'd like!

Here's my config:
```
<plugin>
    <groupId>com.github.temyers</groupId>
    <artifactId>cucumber-jvm-parallel-plugin</artifactId>
    <version>2.0.0</version>
    <executions>
        <execution>
            <id>generateRunners</id>
            <phase>generate-test-sources</phase>
            <goals>
                <goal>generateRunners</goal>
            </goals>
            <configuration>
                <glue>zija.stepdefs</glue>
                <!--<outputDirectory>src/test/java/zija/parallel</outputDirectory>-->
                <featuresDirectory>src/test/resources/zija</featuresDirectory>
                <cucumberOutputDir>target</cucumberOutputDir>
                <format>json</format>
                <strict>false</strict>
                <namingScheme>feature-title</namingScheme>
                <tags>"@staging"</tags>
                <filterFeaturesByTags>true</filterFeaturesByTags>
                <useTestNG>true</useTestNG>
                <!--<namingPattern>ParallelRunner{c}</namingPattern>-->
                <parallelScheme>SCENARIO</parallelScheme>
                <!--<filterScenarioAndOutlineByLines>true</filterScenarioAndOutlineByLines>-->
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by stevejensen22** [comment]
I think the problem is actually with the runner class that's created. The class needs to be generated based on the `tag` but executed based on the `line` number. So the runner class should not contain the `tag`. The `line` number alone is satisfactory after your logic that `ONLY` creates runner classes based on the `tag` with the line number.

Ex:
`Current`
```
import cucumber.api.CucumberOptions;
import cucumber.api.testng.AbstractTestNGCucumberTests;

@CucumberOptions(strict = true,
features = {"src/test/resources/zija/features/japan/Japan MBO My Team Enroll.feature:85"},
plugin = {"json:target/1.json", "pretty"},
monochrome = false,
tags = {"@staging"},
glue = { "zija.stepdefs" })
public class Japanmbomyteamenroll01IT extends AbstractTestNGCucumberTests {
}
```

`Expected`
```
import cucumber.api.CucumberOptions;
import cucumber.api.testng.AbstractTestNGCucumberTests;

@CucumberOptions(strict = true,
features = {"src/test/resources/zija/features/japan/Japan MBO My Team Enroll.feature:85"},
plugin = {"json:target/1.json", "pretty"},
monochrome = false,
glue = { "zija.stepdefs" })
public class Japanmbomyteamenroll01IT extends AbstractTestNGCucumberTests {
}
```

**Comment by temyers** [comment]
@stevejensen22 
Damn, I thought I'd tested that scenario.  I'll look into it.  Alternatively, if you can add a PR with an IT test case to demonstrate that'd be really helpful cheers!

**Comment by sugatmankar** [comment]
@stevejensen22 @temyers 
Please check in closed branch i have already implemented **The class needs to be generated based on the tag but executed based on the line number.**  I have skipped tag getting added when there is line number, Its in template file with one bool variable.

**Pull request closed without merging**
