### PR TITLE
Allow custom templates. Closes #61.

### LINKED ISSUE #61: [feature request] Allow users to specify a custom runner template (.vm file) rather than junit or testng
At the moment, users can choose between junit and testng formats, which changes the runner-template.vm file used to generate the java.

We have the requirement for our runner file to have some additional annotations (eg the test classes extend from a BaseTest class), and so I've forked this project and implemented a custom template.
(fork is here: https://github.com/Frameworkium/cucumber-jvm-parallel-plugin )

I've tried to create a pull request that allows users to specify a <customVmPath> parameter in their pom - alongside the standard parameters for the plugin - to a vm file in their project. For example, it might be in their /resources/ folder: /resources/custom-runner.vm

However, this doesn't work, as Velocity is unable to find the file on the class path (as presumably it's still looking in it's /resources/ folder?)

What do I need to add to make this work, or could a new feature be implemented to enable this?

### PR DESCRIPTION
**Pull request by ham1**
For discussion please see #61.

Usage would be something like:
```xml
...
<plugin>
  <groupId>com.github.temyers</groupId>
  <artifactId>cucumber-jvm-parallel-plugin</artifactId>
  <version>2.0.3</version>
  <executions>
    <execution>
      ...
      <configuration>
        ...
        <!-- custom template -->
        <customVmTemplate>src/test/resources/cucumber-custom-runner.vm</customVmTemplate>
      </configuration>
    </execution>
  </executions>
</plugin>
...
```

### CODE REVIEW

**Comment by temyers** [comment]
Awesome!

Thanks for the contribution.

Please can you update the README.md with the above and some words on configuring it and I'll happy to merge.

**Comment by temyers** [comment]
One more thing:

Please can you create an `it` test to demonstrate the behaviour - under `src/main/it`

**Comment by ham1** [comment]
Will do, certainly by Monday, maybe before.

**Comment by ham1** [comment]
Updated readme and added an IT test.

**Comment by temyers** [comment]
Awesome, thanks for the contribution.

**Pull request merged**
