### PR TITLE
Changes to implement resolution to issue-112

### PR DESCRIPTION
**Pull request by Hyphen31**

### CODE REVIEW

**Comment by mpkorstanje** [comment]
Merged through 1439968157e437f939a77a14a46d43f6bfc39979

**Comment by mpkorstanje** [comment]
Renamed a few things for brevity. Otherwise great patch! Thank you very much.

@temyers all yours.

**Comment by temyers** [comment]
Great, thanks guys.

I'll kick off a release build.

**Comment by temyers** [comment]
It should be in Maven Central shortly.

**Pull request closed without merging**
