### PR TITLE
adds support for multiple output formats (e.g.: html and json)

### PR DESCRIPTION
**Pull request by chrisss404**
allows multiple output formats, for example:

    <format>json,html</format>

### CODE REVIEW

**Comment by temyers** [comment]
Hi,

Thanks for the pull request.  Please could you add an Integration Test under src/it/multiple-format demonstrating use and I'll merge.

Cheers.

**Comment by chrisss404** [comment]
Hi,

can you show me how to execute the integartion tests?

Thanks & regards.

**Comment by temyers** [comment]
Hi,

run

```mvn clean install -Prun-its```

**Comment by chrisss404** [comment]
thx, added test.

**Comment by temyers** [comment]
Thanks,

Merged and released.

cucumber-jvm-parallel-plugin-0.1.2 should be in Maven Central in a couple of hours

**Pull request merged**
