### PR TITLE
Added support for TestNG

### PR DESCRIPTION
**Pull request by tommywo**
Hi, 
I've added posibillty of generating TestNG runners instead of JUnit.
I know I'm missing documentation in readme. 
I will add it add it and in the meantime you can review the code.
Integration tests are copied and modified from junit ones that verify content of generated files.

### CODE REVIEW

**Comment by temyers** [comment]
Hi @tommywo,

Thanks for the contribution.  Looks pretty good.

Comments:
* Move the tests into `src/it/testng` folder.  It will make it easier to track the tests for different frameworks.

* Can you envision mixing JUnit and TestNG tests within a project?  At the moment, this switch is an either/or.  I don't think that's an issue, but I haven't used TestNG myself.

I'll move the JUnit tests into a separate subfolder

**Comment by temyers** [comment]
Added commit 8285c97ab3b4f5e668a9c0d15c08a9a65a069f36 to move the junit tests

**Comment by temyers** [comment]
@tommywo - You had a chance to look at this?

If you can add documentation to the README.md and look at the comments above, I'll merge and release.

**Comment by tommywo** [comment]
I've moved tests to testng folder and bumped version.
I don't think that mixing junit and testng runners are something that user would want to achieve, but i can image we could have separate configs for junit an testng, f.e
```
     <configuration>
         <JUnit>
           <glue>foo, bar</glue>
           <outputDirectory>${project.build.directory}/generated-test-sources/cucumber</outputDirectory>
           <featuresDirectory>src/test/resources/features/junit/</featuresDirectory>
           <cucumberOutputDir>target/cucumber-parallel</cucumberOutputDir>
           <format>json</format>
         </JUnit>
         <TestNG>
           <glue>foo, bar</glue>
           <outputDirectory>${project.build.directory}/generated-test-sources/cucumber</outputDirectory>
           <featuresDirectory>src/test/resources/features/testng/</featuresDirectory>
           <cucumberOutputDir>target/cucumber-parallel</cucumberOutputDir>
           <format>json</format>
         </TestNG>
      </configuration>
``
But I don't even know if maven allows to create such  config.

**Comment by temyers** [comment]
Maven could support it I think, but as you point out, I don't think it would make sense from a user point of view.  It was more a thought experiment :)

**Comment by temyers** [comment]
Sorry for the delat, I've released version 1.1.0 now, including your changes

**Comment by tommywo** [comment]
Great. Thanks :)

**Pull request merged**
