### PR TITLE
Added failing test for issue 150

### PR DESCRIPTION
**Pull request by froemra**
Its a copy of simple-it, only feature1.feature was changed, so it uses the #language-tag. In this case "de" for german. The Gherkin-Keywords were modified accordingly. It should create 2 runners, but fails parsing the german feature.

### CODE REVIEW

**Comment by mpkorstanje** [comment]
The build fails on checkstyle.  @temyers?

**Comment by froemra** [comment]
the same thing happens when i build the clean repo locally, had to comment that section out from maven pom ...

**Comment by temyers** [comment]
Hmm, 

Looks like a Checkstyle property was removed in Checkstyle 8.2

http://checkstyle.sourceforge.net/releasenotes.html

`remove deprecated property maxLineLength from LeftCurlyCheck. Author: rnveach #3671`

The checkstyle report version is currently set to: 
```
<dependencies>
					<dependency>
						<groupId>com.puppycrawl.tools</groupId>
						<artifactId>checkstyle</artifactId>
						<version>LATEST</version>
					</dependency>
				</dependencies>
``` 

I'll remove the failing config.

**Comment by temyers** [comment]
Fixed in 2efd26584d3bf518ead7f34b06430a9b8f589fc5

**Comment by mpkorstanje** [comment]
@froemra you should be able to rebase against master now.

**Comment by froemra** [comment]
thank, you. rebase is done.

**Comment by mpkorstanje** [comment]
The build doesn't fail. Are you reproducing the problem correctly?

**Comment by froemra** [comment]
Tried it today: It fails at my PC at work. It does NOT fail on my private System at home … Seems this is a configuration issue, I’ll have a closer look at it next week and will give feedback.

**Comment by froemra** [comment]
Thanks for your help on the issue. Closing the pull request now, because this seems to be local problem on my dev environment. I cannot reproduce it on GitHub.

**Pull request closed without merging**
